services:
  ultra-coins-website:
    image: ultra-coins-website
    container_name: ultra-coins-website
    build:
      context: .
      dockerfile: ./Dockerfile
    labels:
      traefik.enable: true
      traefik.http.routers.ultra-coins-website.rule: Host(`ultra.coins.tsukuba.ac.jp`)
      traefik.http.services.ultra-coins-website.loadbalancer.server.port: 80
      traefik.http.routers.ultra-coins-website.entrypoints: websecure
      traefik.http.routers.ultra-coins-website.tls: true
    networks:
      - traefik
networks:
  traefik:
    external: true
      
