#timestamp:20251205231756305323553
services:
  ultra-coins-website:
    image: ghcr.io/ultra-coins/ultra-coins-website/website:main
    container_name: ultra-coins-website
    labels:
      traefik.enable: true
      traefik.http.routers.ultra-coins-website.priority: 1
      traefik.http.routers.ultra-coins-website.rule: "Host(`ultra.coins.tsukuba.ac.jp`) && PathPrefix(`/`)"
      traefik.http.services.ultra-coins-website.loadbalancer.server.port: 80
      traefik.http.routers.ultra-coins-website.entrypoints: websecure
      traefik.http.routers.ultra-coins-website.tls: true
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true
